//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file
///
///  Frontend header generated by BOSS for GAMBIT backend Rivet 3.1.4.
///
///  *********************************************
///
///  Authors (add name and date if you modify):
///
///  \author The GAMBIT Collaboration
///
///  *********************************************

#include "gambit/Backends/backend_types/Rivet_3_1_4/identification.hpp"

LOAD_LIBRARY

namespace Gambit
{
   namespace Backends
   {
      namespace Rivet_3_1_4
      {
         namespace Rivet
         {
            typedef ::Rivet_3_1_4::Rivet::AnalysisHandler AnalysisHandler;
         }
      }
   }
}

// Functions
BE_FUNCTION(addAnalysisLibPath, void, (const ::std::basic_string<char, std::char_traits<char>, std::allocator<char> >&), "addAnalysisLibPath__BOSS_3", "addAnalysisLibPath")
// Variables

// Initialisation function (dependencies)

// Convenience functions (registration)


// Convenience functions (definitions)

// End
#include "gambit/Backends/backend_undefs.hpp"
