//
// Frontend header generated by BOSS for GAMBIT backend Rivet 3.1.4.
//

#include "gambit/Backends/backend_types/Rivet_3_1_4/identification.hpp"

LOAD_LIBRARY

namespace Gambit
{
   namespace Backends
   {
      namespace Rivet_3_1_4
      {
         namespace Rivet
         {
            typedef ::Rivet_3_1_4::Rivet::AnalysisHandler AnalysisHandler;
         }
      }
   }
}

// Functions
// Variables

// Initialisation function (dependencies)

// Convenience functions (registration)

// Initialisation function (definition)
BE_INI_FUNCTION{} END_BE_INI_FUNCTION

// Convenience functions (definitions)

// End
#include "gambit/Backends/backend_undefs.hpp"
